WEBPACKER_APP_TEMPLATE_PATH = File.expand_path('../../install/template.rb', __dir__)

namespace :webpacker do
  desc "Install webpacker in this application"
  task :install do
    # Calling exec before invoking app:tempalte will not proceed
    # exec 'yarn --version'
    # Checking yarn binstub will not fail because the binstub rescues the error
    # Either change the yarn binstub template that is generated by rails, or check the global yarn
    # `./bin/yarn --version`
    begin
      # Check yarn global - works, but requires duplicating approach from the binstub,
      # so why not utilize it as the central point of truth for existence of yarn global?
      `yarnpkg --version`
      # Also, the error message is not as friendly, just a backtrace like this:
      # $ rails webpacker:install
      # rails aborted!
      # Errno::ENOENT: No such file or directory - yarnpkg
      # [followed by backtrace to install.rake]
    rescue Errno::ENOENT
      puts 'Yarn is not installed. rails webpacker:install failed!'
      exit false
    end
    if Rails::VERSION::MAJOR >= 5
      exec "./bin/rails app:template LOCATION=#{WEBPACKER_APP_TEMPLATE_PATH}"
    else
      exec "./bin/rake rails:template LOCATION=#{WEBPACKER_APP_TEMPLATE_PATH}"
    end
  end
end
