name: Jest specs

on: [push, pull_request]

permissions:
  contents: read

jobs:
  jest:
    name: Jest specs
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x, 14.x, 16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install yarn maybe
        run: which yarn || npm install -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Jest Specs
        run: yarn test
