name: Code Quality
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  qodana-js:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn

      - name: 'Qodana JS Scan'
        uses: JetBrains/qodana-action@v2022.2.1
        with:
          args: >
            --env,IDEA_PROPERTIES=/data/project/idea.properties,
            --property,property=idea.log.config.file=info.xml

      - name: Upload SARIF report to GitHub
        # Also upload report if quality gate fails
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
